export const PCS_REQUEST_PLAYER_CHARACTERS = "PCS_REQUEST_PLAYER_CHARACTERS";
export const PCS_RECEIVE_PLAYER_CHARACTERS = "PCS_RECEIVE_PLAYER_CHARACTERS";
export const PCS_SELECT_PLAYER_CHARACTER = "PCS_SELECT_PLAYER_CHARACTER";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER_ADD_PROFICIENCY = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER_ADD_PROFICIENCY";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER_REMOVE_PROFICIENCY = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER_REMOVE_PROFICIENCY";
export const PCS_FILTER_PLAYER_CHARACTERS = "PCS_FILTER_PLAYER_CHARACTERS";
export const PCS_SAVE_PLAYER_CHARACTER = "PCS_SAVE_PLAYER_CHARACTER";
export const PCS_SAVED_PLAYER_CHARACTER = "PCS_SAVED_PLAYER_CHARACTER";
export const PCS_REMOVE_PLAYER_CHARACTER = "PCS_REMOVE_PLAYER_CHARACTER";
export const PCS_REMOVED_PLAYER_CHARACTER = "PCS_REMOVED_PLAYER_CHARACTER";

export const CLS_REQUEST_CLASSES = "CLS_REQUEST_CLASSES";
export const CLS_RECEIVE_CLASSES = "CLS_RECEIVE_CLASSES";

export const RCE_REQUEST_RACES = "RCE_REQUEST_RACES";
export const RCE_RECEIVE_RACES = "RCE_RECEIVE_RACES";