export const PCS_REQUEST_PLAYER_CHARACTERS = "PCS_REQUEST_PLAYER_CHARACTERS";
export const PCS_RECEIVE_PLAYER_CHARACTERS = "PCS_RECEIVE_PLAYER_CHARACTERS";
export const PCS_SELECT_PLAYER_CHARACTER = "PCS_SELECT_PLAYER_CHARACTER";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER_ADD_PROFICIENCY = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER_ADD_PROFICIENCY";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER_REMOVE_PROFICIENCY = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER_REMOVE_PROFICIENCY";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER_ADD_ACTION = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER_ADD_ACTION";
export const PCS_UPDATE_SELECTED_PLAYER_CHARACTER_REMOVE_ACTION = "PCS_UPDATE_SELECTED_PLAYER_CHARACTER_REMOVE_ACTION";
export const PCS_FILTER_PLAYER_CHARACTERS = "PCS_FILTER_PLAYER_CHARACTERS";
export const PCS_SAVE_PLAYER_CHARACTER = "PCS_SAVE_PLAYER_CHARACTER";
export const PCS_SAVED_PLAYER_CHARACTER = "PCS_SAVED_PLAYER_CHARACTER";
export const PCS_REMOVE_PLAYER_CHARACTER = "PCS_REMOVE_PLAYER_CHARACTER";
export const PCS_REMOVED_PLAYER_CHARACTER = "PCS_REMOVED_PLAYER_CHARACTER";

export const CLS_REQUEST_CLASSES = "CLS_REQUEST_CLASSES";
export const CLS_RECEIVE_CLASSES = "CLS_RECEIVE_CLASSES";

export const RCE_REQUEST_RACES = "RCE_REQUEST_RACES";
export const RCE_RECEIVE_RACES = "RCE_RECEIVE_RACES";

export const ACT_REQUEST_ACTIONS = "ACT_REQUEST_ACTIONS";
export const ACT_RECEIVE_ACTIONS = "ACT_RECEIVE_ACTIONS";
export const ACT_SELECT_ACTION = "ACT_SELECT_ACTION";
export const ACT_UPDATE_SELECTED_ACTION = "ACT_UPDATE_SELECTED_ACTION";
export const ACT_UPDATE_SELECTED_ACTION_ADD_EFFECT = "ACT_UPDATE_SELECTED_ACTION_ADD_EFFECT";
export const ACT_UPDATE_SELECTED_ACTION_REMOVE_EFFECT = "ACT_UPDATE_SELECTED_ACTION_REMOVE_EFFECT";
export const ACT_SAVE_ACTION = "ACT_SAVE_ACTION";
export const ACT_SAVED_ACTION = "ACT_SAVED_ACTION";
export const ACT_REMOVE_ACTION = "ACT_REMOVE_ACTION";
export const ACT_REMOVED_ACTION = "ACT_REMOVED_ACTION";

export const EFF_REQUEST_EFFECTS = "EFF_REQUEST_EFFECTS";
export const EFF_RECEIVE_EFFECTS = "EFF_RECEIVE_EFFECTS";
export const EFF_SELECT_EFFECT = "EFF_SELECT_EFFECT";
