export const PCS_REQUEST_PLAYER_CHARACTERS = "PCS_REQUEST_PLAYER_CHARACTERS";
export const PCS_RECEIVE_PLAYER_CHARACTERS = "PCS_RECEIVE_PLAYER_CHARACTERS";

export const CLS_REQUEST_CLASSES = "CLS_REQUEST_CLASSES";
export const CLS_RECEIVE_CLASSES = "CLS_RECEIVE_CLASSES";

export const RCE_REQUEST_RACES = "RCE_REQUEST_RACES";
export const RCE_RECEIVE_RACES = "RCE_RECEIVE_RACES";